extends Node

func _ready():
	# setup lahat ng connections haha
	$Lever.connect("state_changed", Callable($AndGate, "set_input").bind(0))
	$Lever5.connect("state_changed", Callable($NotGate, "set_input").bind(0))
	$NotGate.connect("output_changed", Callable($AndGate, "set_input").bind(1))
	$NotGate.connect("output_changed", Callable($OrGate, "set_input").bind(0))
	$Lever4.connect("state_changed", Callable($OrGate, "set_input").bind(1))
	$Lever4.connect("state_changed", Callable($OrGate2, "set_input").bind(0))
	$Lever3.connect("state_changed", Callable($OrGate2, "set_input").bind(1))
	$OrGate2.connect("output_changed", Callable($NotGate3, "set_input").bind(0))
	$OrGate.connect("output_changed", Callable($OrGate3, "set_input").bind(0))
	$NotGate3.connect("output_changed", Callable($OrGate3, "set_input").bind(1))
	$AndGate.connect("output_changed", Callable($AndGate2, "set_input").bind(0))
	$OrGate.connect("output_changed", Callable($AndGate2, "set_input").bind(1))
	$AndGate2.connect("output_changed", Callable($OrGate7, "set_input").bind(0))
	$OrGate3.connect("output_changed", Callable($OrGate7, "set_input").bind(1))
	$OrGate7.connect("output_changed", Callable($NotGate8, "set_input").bind(0))
	$NotGate8.connect("output_changed", Callable($OrGate8, "set_input").bind(0))
	$Lever6.connect("state_changed", Callable($AndGate3, "set_input").bind(0))
	$Lever7.connect("state_changed", Callable($AndGate3, "set_input").bind(1))
	$Lever7.connect("state_changed", Callable($AndGate4, "set_input").bind(0))
	$Lever8.connect("state_changed", Callable($AndGate4, "set_input").bind(1))
	$Lever8.connect("state_changed", Callable($OrGate4, "set_input").bind(0))
	$Lever9.connect("state_changed", Callable($OrGate4, "set_input").bind(1))
	$Lever2.connect("state_changed", Callable($AndGate5, "set_input").bind(1))
	$NotGate3.connect("state_changed", Callable($AndGate5, "set_input").bind(0))
	$AndGate4.connect("output_changed", Callable($NotGate4, "set_input").bind(0))
	$NotGate4.connect("output_changed", Callable($OrGate5, "set_input").bind(0))
	$OrGate4.connect("output_changed", Callable($OrGate5, "set_input").bind(1))
	$AndGate3.connect("output_changed", Callable($OrGate6, "set_input").bind(0))
	$NotGate4.connect("output_changed", Callable($OrGate6, "set_input").bind(1))
	$OrGate6.connect("output_changed", Callable($AndGate8, "set_input").bind(0))
	$OrGate5.connect("output_changed", Callable($AndGate8, "set_input").bind(1))
	$AndGate8.connect("output_changed", Callable($NotGate5, "set_input").bind(0))
	$AndGate5.connect("output_changed", Callable($AndGate7, "set_input").bind(0))
	$OrGate6.connect("output_changed", Callable($AndGate7, "set_input").bind(1))
	$AndGate7.connect("output_changed", Callable($AndGate9, "set_input").bind(0))
	$NotGate5.connect("output_changed", Callable($AndGate9, "set_input").bind(1))
	$AndGate9.connect("output_changed", Callable($NotGate7, "set_input").bind(0))
	$NotGate7.connect("output_changed", Callable($NotGate6, "set_input").bind(0))
	$OrGate3.connect("output_changed", Callable($AndGate6, "set_input").bind(0))
	$AndGate7.connect("output_changed", Callable($AndGate6, "set_input").bind(1))
	$AndGate6.connect("output_changed", Callable($NotGate2, "set_input").bind(0))
	$NotGate8.connect("output_changed", Callable($AndGate11, "set_input").bind(0))
	$NotGate2.connect("output_changed", Callable($AndGate11, "set_input").bind(1))
	$AndGate11.connect("output_changed", Callable($OrGate8, "set_input").bind(1))
	$NotGate2.connect("output_changed", Callable($OrGate9, "set_input").bind(0))
	$NotGate7.connect("output_changed", Callable($OrGate9, "set_input").bind(1))
	$AndGate11.connect("output_changed", Callable($AndGate10, "set_input").bind(0))
	$OrGate9.connect("output_changed", Callable($AndGate10, "set_input").bind(0))

	# Connect to bulb
	$OrGate8.connect("output_changed", Callable($Bulb, "set_state"))
	$AndGate10.connect("output_changed", Callable($Bulb3, "set_state"))
	$NotGate6.connect("output_changed", Callable($Bulb2, "set_state"))
